import {
  PLUGIN_BUILDERS,
  defineConfig,
} from '@bemedev/dev-utils/rolldown';
import { defineConfig as rolldown } from 'rolldown';
import { esmExternalRequirePlugin } from 'rolldown/plugins';

const BANNER = [
  '/*',
  ' * This file is auto-generated by rolldown.',
  ' * Do not edit this file directly.',
  ' */',
  ' ',
].join('\n');

const FOOTER = [
  ' ',
  '/*',
  'Enjoy it! -',
  'CRedits :',
  '@chlbri : https://github.com/chlbri',
  '*/',
].join('\n');

export default rolldown([
  {
    input: 'src/action.ts',
    platform: 'node',

    output: {
      file: 'dist/action.js',
      format: 'esm',
      sourcemap: false,
      postBanner: BANNER,
      postFooter: FOOTER,
      minify: true,
      name: 'github-action',
    },

    plugins: [
      PLUGIN_BUILDERS.alias(),
      PLUGIN_BUILDERS.tsPaths({ colors: true }),
      PLUGIN_BUILDERS.externals({
        deps: false,
        peerDeps: false,
        optDeps: false,
      }),
      esmExternalRequirePlugin(),
    ],
  },

  defineConfig.bemedev({
    declarationMap: true,
    ignoresJS: '**/*.example.ts',
  }),
]);
