name: Publish

on:
  push:
    branches:
      - main
      - master
      - beta
      - canary

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout pnpm repo
        uses: chlbri/node-github-actions/.github/actions/pnpmi@main

      - name: Build
        run: pnpm run build

      - name: Publish
        run: node action.js
        id: publish

      - name: Check - updated
        if: ${{ steps.publish.outputs.type }}
        run: echo "${{ steps.publish.outputs.name }} Version changed from ${{
          steps.publish.outputs.old-version }} to ${{
          steps.publish.outputs.version }}"

      - name: Check - not updated
        if: ${{ ! steps.publish.outputs.type }}
        run: echo "Remain the same! - ${{ steps.publish.outputs.version }}"

      - name: GitHub Tag
        if: ${{ steps.publish.outputs.released }}
        uses: chlbri/node-github-actions/.github/actions/tag@main
        with:
          tag: ${{ steps.publish.outputs.new-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
